copyright: Copyright 2022 StrangeBee. All rights reserved.
site_name: TheHive 5 Documentation
site_url: https://docs.strangebee.com
theme:
  name: material
  custom_dir: ./overrides/
  logo: 'assets/images/strangebee.svg'
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: datetime
  - redirects:
        # redirect_maps:
        #     'thehive/index.md': 'thehive/setup/index.md'

repo_name: "StrangeBeeCorp/docs"
repo_url: "https://github.com/StrangeBeeCorp/docs"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: "https://www.linkedin.com/company/strangebee"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/StrangeBee"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/channel/UCUmojqcxiG_LUbe62pR2Igg"

markdown_extensions:
  - toc:
      permalink: "#"
  - attr_list
  - def_list
  - codehilite
  - admonition
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg